[toolchain]
channel = "stable"
targets = [
    # iOS
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",

    # macOS
    "aarch64-apple-darwin",

    # Android
    "aarch64-linux-android",
    "x86_64-linux-android",
]
components = ["clippy", "rustfmt"]
